/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-09-16 17:37:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Head_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1629130510000L));
    _jspx_dependants.put("jar:file:/D:/phimmoi/apache-tomcat-9.0.46/webapps/phimmoi/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /Head.jsp(4,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${categoryPhimBo!=null||categoryPhimLe!=null||categoryPhimChieuRap!=null||categoryPhimHoatHinh!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	<div class=\"container\">\r\n");
          out.write("		<div class=\"row\">\r\n");
          out.write("			<div class=\"col-lg-9\">\r\n");
          out.write("				<h1 style=\"line-height: 60px; height: 50px;\">\r\n");
          out.write("					<a href=\"home\" class=\"nav-link\" style=\"color: rgb(240, 240, 240);\">PHIM\r\n");
          out.write("						MOI</a>\r\n");
          out.write("				</h1>\r\n");
          out.write("			</div>\r\n");
          out.write("\r\n");
          out.write("			<div class=\"col-lg-3\" style=\"margin-top: 22px;\">\r\n");
          out.write("				<form class=\"form-inline my-2 my-lg-0\">\r\n");
          out.write("					<div class=\"input-group input-group-sm\" style=\"width: 100%;\">\r\n");
          out.write("						<input oninput=\"searchByName(this)\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${txt }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" type=\"text\"\r\n");
          out.write("							class=\"form-control\" aria-label=\"Small\"\r\n");
          out.write("							aria-describedby=\"inputGroup-sizing-sm\"\r\n");
          out.write("							placeholder=\"Tìm kiếm theo tên phim\">\r\n");
          out.write("						<div class=\"input-group-append\">\r\n");
          out.write("							<div class=\"btn btn-number\"\r\n");
          out.write("								style=\"background-color: rgb(255, 200, 50);\">\r\n");
          out.write("								<i class=\"bi bi-search\" style=\"color: white;\"></i>\r\n");
          out.write("							</div>\r\n");
          out.write("						</div>\r\n");
          out.write("					</div>\r\n");
          out.write("				</form>\r\n");
          out.write("			</div>\r\n");
          out.write("		</div>\r\n");
          out.write("	</div>\r\n");
          out.write("\r\n");
          out.write("	<hr\r\n");
          out.write("		style=\"height: 3px; border: none; background-color: rgb(255, 200, 50);\">\r\n");
          out.write("\r\n");
          out.write("	<div class=\"container\">\r\n");
          out.write("		<nav>\r\n");
          out.write("			<div class=\"btn-group\">\r\n");
          out.write("				<button type=\"button\"\r\n");
          out.write("					class=\"btn btn-secondary dropdown-toggle menu1\"\r\n");
          out.write("					data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Phim\r\n");
          out.write("					bộ</button>\r\n");
          out.write("				<div class=\"dropdown-menu dropdown-menu-right\">\r\n");
          out.write("					");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("				</div>\r\n");
          out.write("			</div>\r\n");
          out.write("			<div class=\"btn-group\">\r\n");
          out.write("				<button type=\"button\"\r\n");
          out.write("					class=\"btn btn-secondary dropdown-toggle  menu1\"\r\n");
          out.write("					data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Phim\r\n");
          out.write("					lẻ</button>\r\n");
          out.write("				<div class=\"dropdown-menu dropdown-menu-right\">\r\n");
          out.write("					");
          if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("				</div>\r\n");
          out.write("			</div>\r\n");
          out.write("			<div class=\"btn-group\">\r\n");
          out.write("				<button type=\"button\"\r\n");
          out.write("					class=\"btn btn-secondary dropdown-toggle menu1\"\r\n");
          out.write("					data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Phim\r\n");
          out.write("					chiếu rạp</button>\r\n");
          out.write("				<div class=\"dropdown-menu dropdown-menu-right\">\r\n");
          out.write("					");
          if (_jspx_meth_c_005fforEach_005f2(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("				</div>\r\n");
          out.write("			</div>\r\n");
          out.write("			<div class=\"btn-group\">\r\n");
          out.write("				<button type=\"button\"\r\n");
          out.write("					class=\"btn btn-secondary dropdown-toggle menu1\"\r\n");
          out.write("					data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Phim\r\n");
          out.write("					hoạt hình</button>\r\n");
          out.write("				<div class=\"dropdown-menu dropdown-menu-right\">\r\n");
          out.write("					");
          if (_jspx_meth_c_005fforEach_005f3(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("				</div>\r\n");
          out.write("			</div>\r\n");
          out.write("			");
          if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("			");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("			");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("			");
          if (_jspx_meth_c_005fif_005f4(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("			");
          if (_jspx_meth_c_005fif_005f5(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("			");
          if (_jspx_meth_c_005fif_005f6(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("		</nav>\r\n");
          out.write("		<hr\r\n");
          out.write("			style=\"height: 1px; border: none; background-color: rgb(240, 240, 240);\">\r\n");
          out.write("	</div>\r\n");
          out.write("	<!-- Add -->\r\n");
          out.write("	<div class=\"modal fade\" id=\"add\" tabindex=\"-1\"\r\n");
          out.write("		aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
          out.write("		<div class=\"modal-dialog\">\r\n");
          out.write("			<div class=\"modal-content\">\r\n");
          out.write("				<div class=\"modal-header\">\r\n");
          out.write("					<h5 class=\"modal-title\" id=\"exampleModalLabel\">Thêm phim</h5>\r\n");
          out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
          out.write("						aria-label=\"Close\">\r\n");
          out.write("						<span aria-hidden=\"true\">&times;</span>\r\n");
          out.write("					</button>\r\n");
          out.write("				</div>\r\n");
          out.write("				<form action=\"add\" method=\"post\">\r\n");
          out.write("					<div class=\"modal-body\">\r\n");
          out.write("						<label for=\"type\"><b>Kiểu:</b></label> <input required=\"required\"\r\n");
          out.write("							type=\"text\" class=\"form-control\" name=\"type\" id=\"type\"><label\r\n");
          out.write("							for=\"category\"><b>Thể loại:</b></label> <input\r\n");
          out.write("							required=\"required\" type=\"text\" class=\"form-control\"\r\n");
          out.write("							name=\"category\" id=\"category\"><label for=\"episode\"><b>Tập:</b></label>\r\n");
          out.write("						<input required=\"required\" type=\"text\" class=\"form-control\"\r\n");
          out.write("							name=\"episode\" id=\"episode\"><label for=\"episodeURL\"><b>URL:</b></label>\r\n");
          out.write("						<input required=\"required\" type=\"text\" class=\"form-control\"\r\n");
          out.write("							name=\"episodeURL\" id=\"episodeURL\"><label for=\"imageURL\"><b>Ảnh:</b></label>\r\n");
          out.write("						<input required=\"required\" type=\"text\" class=\"form-control\"\r\n");
          out.write("							name=\"imageURL\" id=\"imageURL\"><label for=\"title\"><b>Tiêu\r\n");
          out.write("								đề:</b></label> <input required=\"required\" type=\"text\" class=\"form-control\"\r\n");
          out.write("							name=\"title\" id=\"title\">\r\n");
          out.write("					</div>\r\n");
          out.write("					<div class=\"modal-footer\">\r\n");
          out.write("						<button type=\"submit\" class=\"btn btn-primary\">Cập nhật</button>\r\n");
          out.write("					</div>\r\n");
          out.write("				</form>\r\n");
          out.write("			</div>\r\n");
          out.write("		</div>\r\n");
          out.write("	</div>\r\n");
          out.write("	<!-- Get report -->\r\n");
          out.write("	<div class=\"modal fade\" id=\"report\" tabindex=\"-1\"\r\n");
          out.write("		aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
          out.write("		<div class=\"modal-dialog\">\r\n");
          out.write("			<div class=\"modal-content\">\r\n");
          out.write("				<div class=\"modal-header\">\r\n");
          out.write("					<h5 class=\"modal-title\" id=\"exampleModalLabel\">Báo lỗi</h5>\r\n");
          out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
          out.write("						aria-label=\"Close\">\r\n");
          out.write("						<span aria-hidden=\"true\">&times;</span>\r\n");
          out.write("					</button>\r\n");
          out.write("				</div>\r\n");
          out.write("				<div class=\"modal-body\">\r\n");
          out.write("					<ul>\r\n");
          out.write("						");
          if (_jspx_meth_c_005fforEach_005f4(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("					</ul>\r\n");
          out.write("				</div>\r\n");
          out.write("\r\n");
          out.write("			</div>\r\n");
          out.write("		</div>\r\n");
          out.write("	</div>\r\n");
          out.write("	<!-- Get history -->\r\n");
          out.write("	<div class=\"modal fade\" id=\"history\" tabindex=\"-1\"\r\n");
          out.write("		aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
          out.write("		<div class=\"modal-dialog modal-lg\">\r\n");
          out.write("			<div class=\"modal-content\">\r\n");
          out.write("				<div class=\"modal-header\">\r\n");
          out.write("					<h5 class=\"modal-title\" id=\"exampleModalLabel\">Lịch sử</h5>\r\n");
          out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
          out.write("						aria-label=\"Close\">\r\n");
          out.write("						<span aria-hidden=\"true\">&times;</span>\r\n");
          out.write("					</button>\r\n");
          out.write("				</div>\r\n");
          out.write("				<div class=\"modal-body\">\r\n");
          out.write("					<ul>\r\n");
          out.write("						");
          if (_jspx_meth_c_005fforEach_005f5(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("					</ul>\r\n");
          out.write("				</div>\r\n");
          out.write("\r\n");
          out.write("			</div>\r\n");
          out.write("		</div>\r\n");
          out.write("	</div>\r\n");
          out.write("	<!-- admin -->\r\n");
          out.write("	<div class=\"modal fade\" id=\"admin\" tabindex=\"-1\"\r\n");
          out.write("		aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
          out.write("		<div class=\"modal-dialog\">\r\n");
          out.write("			<div class=\"modal-content\">\r\n");
          out.write("				<div class=\"modal-header\">\r\n");
          out.write("					<h5 class=\"modal-title\" id=\"exampleModalLabel\">Admin</h5>\r\n");
          out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
          out.write("						aria-label=\"Close\">\r\n");
          out.write("						<span aria-hidden=\"true\">&times;</span>\r\n");
          out.write("					</button>\r\n");
          out.write("				</div>\r\n");
          out.write("				<div class=\"modal-body\">\r\n");
          out.write("					<form action=\"update-email\" method=\"post\">\r\n");
          out.write("						<div class=\"row\">\r\n");
          out.write("							<div class=\"col-1\"></div>\r\n");
          out.write("							<div class=\"col-10\">\r\n");
          out.write("								<label for=\"account\"><b>Tài khoản:</b></label>\r\n");
          out.write("							</div>\r\n");
          out.write("							<div class=\"col-1\"></div>\r\n");
          out.write("						</div>\r\n");
          out.write("						<div class=\"row\">\r\n");
          out.write("							<div class=\"col-1\"></div>\r\n");
          out.write("							<div class=\"col-10\">\r\n");
          out.write("								<input readonly=\"readonly\" type=\"text\" class=\"form-control\"\r\n");
          out.write("									value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.admin.account}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" id=\"account\">\r\n");
          out.write("							</div>\r\n");
          out.write("							<div class=\"col-1\"></div>\r\n");
          out.write("						</div>\r\n");
          out.write("						<div class=\"row\">\r\n");
          out.write("							<div class=\"col-1\"></div>\r\n");
          out.write("							<div class=\"col-10\">\r\n");
          out.write("								<label for=\"email\"><b>Email:</b></label>\r\n");
          out.write("							</div>\r\n");
          out.write("							<div class=\"col-1\"></div>\r\n");
          out.write("						</div>\r\n");
          out.write("						<div class=\"row\">\r\n");
          out.write("							<div class=\"col-1\"></div>\r\n");
          out.write("							<div class=\"col-10\">\r\n");
          out.write("								<input required=\"required\" type=\"email\" class=\"form-control\"\r\n");
          out.write("									name=\"email\" id=\"email\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.admin.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("							</div>\r\n");
          out.write("							<div class=\"col-1\"></div>\r\n");
          out.write("						</div>\r\n");
          out.write("						<input name=\"id\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.admin.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("							style=\"display: none;\" id=\"_id\">\r\n");
          out.write("						<div class=\"row\">\r\n");
          out.write("							<div class=\"col-1\"></div>\r\n");
          out.write("							<div class=\"col-10\">\r\n");
          out.write("								<label for=\"password\"><b>Mật khẩu cũ:</b></label>\r\n");
          out.write("							</div>\r\n");
          out.write("							<div class=\"col-1\"></div>\r\n");
          out.write("						</div>\r\n");
          out.write("						<div class=\"row\">\r\n");
          out.write("							<div class=\"col-1\"></div>\r\n");
          out.write("							<div class=\"col-10\">\r\n");
          out.write("								<input oninput=\"checkPassword1(this)\" required=\"required\"\r\n");
          out.write("									type=\"password\" class=\"form-control\" id=\"password\"\r\n");
          out.write("									name=\"password\"> <sup><a href=\"get-password\">Quên\r\n");
          out.write("										mật khẩu</a></sup>\r\n");
          out.write("							</div>\r\n");
          out.write("							<div class=\"col-1\" style=\"margin-top: 5px;\" id=\"pass1\"></div>\r\n");
          out.write("						</div>\r\n");
          out.write("						<div class=\"row\">\r\n");
          out.write("							<div class=\"col-1\"></div>\r\n");
          out.write("							<div class=\"col-10\">\r\n");
          out.write("								<button style=\"margin: 15px 0 15px 0;\" type=\"submit\"\r\n");
          out.write("									class=\"btn btn-primary\">Cập nhật</button>\r\n");
          out.write("							</div>\r\n");
          out.write("							<div class=\"col-1\"></div>\r\n");
          out.write("						</div>\r\n");
          out.write("					</form>\r\n");
          out.write("					<form action=\"update-password\" onsubmit=\"return confirmm()\"\r\n");
          out.write("						method=\"post\">\r\n");
          out.write("						<input name=\"id\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.admin.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("							style=\"display: none;\" id=\"_id\">\r\n");
          out.write("						<div class=\"row\">\r\n");
          out.write("							<div class=\"col-1\"></div>\r\n");
          out.write("							<div class=\"col-10\">\r\n");
          out.write("								<label for=\"password\"><b>Mật khẩu cũ:</b></label>\r\n");
          out.write("							</div>\r\n");
          out.write("							<div class=\"col-1\"></div>\r\n");
          out.write("						</div>\r\n");
          out.write("						<div class=\"row\">\r\n");
          out.write("							<div class=\"col-1\"></div>\r\n");
          out.write("							<div class=\"col-10\">\r\n");
          out.write("								<input oninput=\"checkPassword2(this)\" required=\"required\"\r\n");
          out.write("									type=\"password\" class=\"form-control\" id=\"password\"\r\n");
          out.write("									name=\"password\"> <sup><a href=\"get-password\">Quên\r\n");
          out.write("										mật khẩu</a></sup>\r\n");
          out.write("							</div>\r\n");
          out.write("							<div class=\"col-1\" style=\"margin-top: 5px;\" id=\"pass2\"></div>\r\n");
          out.write("						</div>\r\n");
          out.write("						<div class=\"row\">\r\n");
          out.write("							<div class=\"col-1\"></div>\r\n");
          out.write("							<div class=\"col-10\">\r\n");
          out.write("								<label for=\"newpass\"><b>Mật khẩu mới:</b></label>\r\n");
          out.write("							</div>\r\n");
          out.write("							<div class=\"col-1\"></div>\r\n");
          out.write("						</div>\r\n");
          out.write("						<div class=\"row\">\r\n");
          out.write("							<div class=\"col-1\"></div>\r\n");
          out.write("							<div class=\"col-10\">\r\n");
          out.write("								<input oninput=\"newPass()\" required=\"required\" type=\"password\"\r\n");
          out.write("									class=\"form-control\" name=\"newpass\" id=\"newpass\"> <sup\r\n");
          out.write("									id=\"a\" class=\"text-danger\" style=\"display: none;\">Mật\r\n");
          out.write("									khẩu yếu</sup>\r\n");
          out.write("							</div>\r\n");
          out.write("							<div class=\"col-1\" style=\"margin-top: 5px;\">\r\n");
          out.write("								<i id=\"b\" class=\"bi bi-x-circle text-danger\"\r\n");
          out.write("									style=\"display: none;\"></i> <i id=\"c\"\r\n");
          out.write("									class=\"bi bi-check-circle text-success\" style=\"display: none;\"></i>\r\n");
          out.write("							</div>\r\n");
          out.write("						</div>\r\n");
          out.write("						<div class=\"row\">\r\n");
          out.write("							<div class=\"col-1\"></div>\r\n");
          out.write("							<div class=\"col-10\">\r\n");
          out.write("								<label for=\"confirm\"><b>Xác nhận mật khẩu:</b></label>\r\n");
          out.write("\r\n");
          out.write("							</div>\r\n");
          out.write("							<div class=\"col-1\"></div>\r\n");
          out.write("						</div>\r\n");
          out.write("						<div class=\"row\">\r\n");
          out.write("							<div class=\"col-1\"></div>\r\n");
          out.write("							<div class=\"col-10\">\r\n");
          out.write("								<input oninput=\"confirmm()\" required=\"required\" type=\"password\"\r\n");
          out.write("									class=\"form-control\" name=\"confirm\" id=\"confirm\"> <sup\r\n");
          out.write("									id=\"d\" class=\"text-danger\" style=\"display: none;\">Mật\r\n");
          out.write("									khẩu không khớp</sup>\r\n");
          out.write("							</div>\r\n");
          out.write("							<div class=\"col-1\" style=\"margin-top: 5px;\">\r\n");
          out.write("								<i id=\"e\" class=\"bi bi-x-circle text-danger\"\r\n");
          out.write("									style=\"display: none;\"></i> <i id=\"f\"\r\n");
          out.write("									class=\"bi bi-check-circle text-success\" style=\"display: none;\"></i>\r\n");
          out.write("							</div>\r\n");
          out.write("						</div>\r\n");
          out.write("						<div class=\"row\">\r\n");
          out.write("							<div class=\"col-1\"></div>\r\n");
          out.write("							<div class=\"col-10\">\r\n");
          out.write("								<button style=\"margin-top: 15px; display: none;\" type=\"submit\"\r\n");
          out.write("									id=\"submit\" class=\"btn btn-primary\">Cập nhật</button>\r\n");
          out.write("							</div>\r\n");
          out.write("							<div class=\"col-1\"></div>\r\n");
          out.write("						</div>\r\n");
          out.write("					</form>\r\n");
          out.write("				</div>\r\n");
          out.write("			</div>\r\n");
          out.write("		</div>\r\n");
          out.write("	</div>\r\n");
          out.write("	<script>\r\n");
          out.write("		function checkPassword1(param) {\r\n");
          out.write("			let password = param.value;\r\n");
          out.write("			let _id = document.getElementById(\"_id\").value;\r\n");
          out.write("			$.ajax({\r\n");
          out.write("				url : \"/phimmoi/check-password\",\r\n");
          out.write("				type : \"post\",\r\n");
          out.write("				data : {\r\n");
          out.write("					pass : password,\r\n");
          out.write("					id : _id\r\n");
          out.write("				},\r\n");
          out.write("				success : function(data) {\r\n");
          out.write("					let row = document.getElementById(\"pass1\");\r\n");
          out.write("					row.innerHTML = data;\r\n");
          out.write("				}\r\n");
          out.write("\r\n");
          out.write("			});\r\n");
          out.write("		}\r\n");
          out.write("		function checkPassword2(param) {\r\n");
          out.write("			let password = param.value;\r\n");
          out.write("			let _id = document.getElementById(\"_id\").value;\r\n");
          out.write("			$.ajax({\r\n");
          out.write("				url : \"/phimmoi/check-password\",\r\n");
          out.write("				type : \"post\",\r\n");
          out.write("				data : {\r\n");
          out.write("					pass : password,\r\n");
          out.write("					id : _id\r\n");
          out.write("				},\r\n");
          out.write("				success : function(data) {\r\n");
          out.write("					let row = document.getElementById(\"pass2\");\r\n");
          out.write("					row.innerHTML = data;\r\n");
          out.write("				}\r\n");
          out.write("\r\n");
          out.write("			});\r\n");
          out.write("		}\r\n");
          out.write("\r\n");
          out.write("		function newPass() {\r\n");
          out.write("			let newpass = document.getElementById(\"newpass\").value;\r\n");
          out.write("			if (newpass.length >= 6 && /[\\d]/.test(newpass)\r\n");
          out.write("					&& /[a-z]/.test(newpass) && /[A-Z]/.test(newpass)\r\n");
          out.write("					&& /[\\W]/.test(newpass) && /[\\w]/.test(newpass)) {\r\n");
          out.write("				document.getElementById(\"a\").style.display = \"none\";\r\n");
          out.write("				document.getElementById(\"c\").style.display = \"inline\";\r\n");
          out.write("				document.getElementById(\"b\").style.display = \"none\";\r\n");
          out.write("			} else {\r\n");
          out.write("				document.getElementById(\"a\").style.display = \"inline\";\r\n");
          out.write("				document.getElementById(\"c\").style.display = \"none\";\r\n");
          out.write("				document.getElementById(\"b\").style.display = \"inline\";\r\n");
          out.write("			}\r\n");
          out.write("			confirmm();\r\n");
          out.write("		}\r\n");
          out.write("\r\n");
          out.write("		function confirmm() {\r\n");
          out.write("			let confirm = document.getElementById(\"confirm\").value;\r\n");
          out.write("			let newpass = document.getElementById(\"newpass\").value;\r\n");
          out.write("			{\r\n");
          out.write("				if (confirm == newpass) {\r\n");
          out.write("					document.getElementById(\"d\").style.display = \"none\";\r\n");
          out.write("					document.getElementById(\"f\").style.display = \"inline\";\r\n");
          out.write("					document.getElementById(\"e\").style.display = \"none\";\r\n");
          out.write("				} else {\r\n");
          out.write("					document.getElementById(\"d\").style.display = \"inline\";\r\n");
          out.write("					document.getElementById(\"f\").style.display = \"none\";\r\n");
          out.write("					document.getElementById(\"e\").style.display = \"inline\";\r\n");
          out.write("				}\r\n");
          out.write("			}\r\n");
          out.write("			{\r\n");
          out.write("				if (newpass.length >= 6 && /[\\d]/.test(newpass)\r\n");
          out.write("						&& /[a-z]/.test(newpass) && /[A-Z]/.test(newpass)\r\n");
          out.write("						&& /[\\W]/.test(newpass) && /[\\w]/.test(newpass)\r\n");
          out.write("						&& confirm == newpass) {\r\n");
          out.write("					document.getElementById(\"submit\").style.display = \"inline\";\r\n");
          out.write("				} else {\r\n");
          out.write("					document.getElementById(\"submit\").style.display = \"none\";\r\n");
          out.write("				}\r\n");
          out.write("			}\r\n");
          out.write("			return newpass.length >= 6 && /[\\d]/.test(newpass)\r\n");
          out.write("					&& /[a-z]/.test(newpass) && /[A-Z]/.test(newpass)\r\n");
          out.write("					&& /[\\W]/.test(newpass) && /[\\w]/.test(newpass)\r\n");
          out.write("					&& confirm == newpass;\r\n");
          out.write("		}\r\n");
          out.write("	</script>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /Head.jsp(45,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/Head.jsp(45,5) '${categoryPhimBo}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${categoryPhimBo}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /Head.jsp(45,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("o");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("						<a class=\"dropdown-item menu2\"\r\n");
            out.write("							href=\"search?type=Phim%20bộ&category=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /Head.jsp(57,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/Head.jsp(57,5) '${categoryPhimLe}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${categoryPhimLe}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /Head.jsp(57,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("o");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("						<a class=\"dropdown-item menu2\"\r\n");
            out.write("							href=\"search?type=Phim%20lẻ&category=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /Head.jsp(69,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/Head.jsp(69,5) '${categoryPhimChieuRap}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${categoryPhimChieuRap}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /Head.jsp(69,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("o");
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("						<a class=\"dropdown-item menu2\"\r\n");
            out.write("							href=\"search?type=Phim%20chiếu%20rạp&category=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f3_reused = false;
    try {
      _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /Head.jsp(81,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setItems(new org.apache.jasper.el.JspValueExpression("/Head.jsp(81,5) '${categoryPhimHoatHinh}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${categoryPhimHoatHinh}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /Head.jsp(81,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setVar("o");
      int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
        if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("						<a class=\"dropdown-item menu2\"\r\n");
            out.write("							href=\"search?type=Phim%20hoạt%20hình&category=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
      _jspx_th_c_005fforEach_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /Head.jsp(87,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.admin!=null || sessionScope.user!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<div class=\"btn-group\">\r\n");
          out.write("					<a href=\"logout\"><button type=\"button\"\r\n");
          out.write("							class=\"btn btn-secondary menu1\">Đăng xuất</button></a>\r\n");
          out.write("				</div>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /Head.jsp(93,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.admin!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<div class=\"btn-group\">\r\n");
          out.write("					<button data-toggle=\"modal\" data-target=\"#admin\" type=\"button\"\r\n");
          out.write("						class=\"btn btn-secondary menu1\">Admin</button>\r\n");
          out.write("				</div>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /Head.jsp(99,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.admin!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<div class=\"btn-group\">\r\n");
          out.write("					<button data-toggle=\"modal\" data-target=\"#add\" type=\"button\"\r\n");
          out.write("						class=\"btn btn-secondary menu1\">\r\n");
          out.write("						<i class=\"bi bi-plus-circle\"></i>\r\n");
          out.write("					</button>\r\n");
          out.write("				</div>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /Head.jsp(107,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.admin!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<div class=\"btn-group\">\r\n");
          out.write("					<button data-toggle=\"modal\" data-target=\"#report\" type=\"button\"\r\n");
          out.write("						class=\"btn btn-secondary menu1\">\r\n");
          out.write("						<i class=\"bi bi-bell-fill\"></i>\r\n");
          out.write("					</button>\r\n");
          out.write("				</div>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /Head.jsp(115,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<div class=\"btn-group\">\r\n");
          out.write("					<button data-toggle=\"modal\" data-target=\"#history\" type=\"button\"\r\n");
          out.write("						class=\"btn btn-secondary menu1\">\r\n");
          out.write("						<i class=\"bi bi-clock-history\"></i>\r\n");
          out.write("					</button>\r\n");
          out.write("				</div>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /Head.jsp(123,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user==null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<div class=\"btn-group\">\r\n");
          out.write("					<a\r\n");
          out.write("						href=\"https://www.facebook.com/dialog/oauth?client_id=667188987589328&redirect_uri=https://localhost:8443/phimmoi/login-facebook\"><button\r\n");
          out.write("							type=\"button\" class=\"btn btn-secondary menu1\">Đăng nhập</button></a>\r\n");
          out.write("				</div>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f4 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f4_reused = false;
    try {
      _jspx_th_c_005fforEach_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /Head.jsp(183,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setItems(new org.apache.jasper.el.JspValueExpression("/Head.jsp(183,6) '${report}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${report}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /Head.jsp(183,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setVar("o");
      int[] _jspx_push_body_count_c_005fforEach_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f4 = _jspx_th_c_005fforEach_005f4.doStartTag();
        if (_jspx_eval_c_005fforEach_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("							<li><a href=\"report?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"nav-link\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></li>\r\n");
            out.write("						");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f4.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f4);
      _jspx_th_c_005fforEach_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f5 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f5_reused = false;
    try {
      _jspx_th_c_005fforEach_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /Head.jsp(206,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f5.setItems(new org.apache.jasper.el.JspValueExpression("/Head.jsp(206,6) '${history}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${history}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /Head.jsp(206,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f5.setVar("o");
      int[] _jspx_push_body_count_c_005fforEach_005f5 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f5 = _jspx_th_c_005fforEach_005f5.doStartTag();
        if (_jspx_eval_c_005fforEach_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("							<li><a href=\"detail?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"nav-link\"> <span> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </span><span style=\"color: red;\"> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.time }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </span>\r\n");
            out.write("							</a></li>\r\n");
            out.write("						");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f5.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f5[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f5.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f5.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f5);
      _jspx_th_c_005fforEach_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f5_reused);
    }
    return false;
  }
}
