/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-09-25 02:26:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class WatchMovie_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1629130510000L));
    _jspx_dependants.put("jar:file:/D:/phimmoi/apache-tomcat-9.0.46/webapps/phimmoi/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"vi-VN\">\n");
      out.write("<head>\n");
      out.write("<!-- Required meta tags -->\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("<!-- Bootstrap CSS -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css\"\n");
      out.write("	integrity=\"sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("<!-- Bootstrap JS -->\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"\n");
      out.write("	integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("<script\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js\"\n");
      out.write("	integrity=\"sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("<!-- Bootstrap ICON -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\">\n");
      out.write("<!-- font google -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Sofia\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;0,900;1,100;1,300;1,700&family=Sen:wght@400;700;800&display=swap\" rel=\"stylesheet\">\n");
      out.write("<!-- jquery -->\n");
      out.write("<script\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("<!-- fontawesome -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.15.4/css/all.css\" integrity=\"sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm\" crossorigin=\"anonymous\">\n");
      out.write("<title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${phim.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".menu1:hover {\n");
      out.write("	color: rgb(255, 200, 50);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".menu2:hover {\n");
      out.write("	color: white;\n");
      out.write("	background-color: #708090;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".ifra {\n");
      out.write("	height: 620px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media screen and (max-width: 1000px) {\n");
      out.write("	.ifra {\n");
      out.write("		height: 556px;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media screen and (max-width: 950px) {\n");
      out.write("	.ifra {\n");
      out.write("		height: 528px;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media screen and (max-width: 900px) {\n");
      out.write("	.ifra {\n");
      out.write("		height: 500px;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media screen and (max-width: 850px) {\n");
      out.write("	.ifra {\n");
      out.write("		height: 472px;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media screen and (max-width: 800px) {\n");
      out.write("	.ifra {\n");
      out.write("		height: 444px;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media screen and (max-width: 750px) {\n");
      out.write("	.ifra {\n");
      out.write("		height: 417px;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media screen and (max-width: 700px) {\n");
      out.write("	.ifra {\n");
      out.write("		height: 389px;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media screen and (max-width: 650px) {\n");
      out.write("	.ifra {\n");
      out.write("		height: 361px;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media screen and (max-width: 600px) {\n");
      out.write("	.ifra {\n");
      out.write("		height: 333px;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media screen and (max-width: 550px) {\n");
      out.write("	.ifra {\n");
      out.write("		height: 306px;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media screen and (max-width: 500px) {\n");
      out.write("	.ifra {\n");
      out.write("		height: 278px;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media screen and (max-width: 450px) {\n");
      out.write("	.ifra {\n");
      out.write("		height: 250px;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media screen and (max-width: 400px) {\n");
      out.write("	.ifra {\n");
      out.write("		height: 222px;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write("ul.root > li{\n");
      out.write("    list-style: none;\n");
      out.write("    float: left;\n");
      out.write("    position: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write("ul.root > li > a{\n");
      out.write("	font-size: 20px;\n");
      out.write("    text-decoration: none;\n");
      out.write("    color: #fff;\n");
      out.write("    padding: 0px 15px;\n");
      out.write("    line-height: 40px;\n");
      out.write("    display: block;\n");
      out.write("}\n");
      out.write("\n");
      out.write("ul.root > li > a:hover{\n");
      out.write("    background-color: white;\n");
      out.write("    color: rgb(255, 200, 50);\n");
      out.write("    transition: ease-in 0.35s;\n");
      out.write("    -moz-transition: ease-in 0.35s;\n");
      out.write("    -webkit-transition: ease-in 0.35s;\n");
      out.write("}\n");
      out.write("\n");
      out.write("ul.sub-menu {\n");
      out.write("	font-size: 15px;\n");
      out.write("    display: none;\n");
      out.write("    background-color: #fff;\n");
      out.write("    width: 350px;\n");
      out.write("    position: absolute;\n");
      out.write("    columns: 2;\n");
      out.write("}\n");
      out.write("\n");
      out.write("ul.sub-menu li{\n");
      out.write("    list-style: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("ul.sub-menu li a{\n");
      out.write("    color: black;\n");
      out.write("    text-decoration: none;\n");
      out.write("    display: block;\n");
      out.write("    line-height: 40px;\n");
      out.write("    text-indent: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("ul.sub-menu li a:hover{\n");
      out.write("    background-color: lightgray;\n");
      out.write("    transition: ease-in 0.35s;\n");
      out.write("    -moz-transition: ease-in 0.35s;\n");
      out.write("    -webkit-transition: ease-in 0.35s;\n");
      out.write("}\n");
      out.write("\n");
      out.write("ul.root > li:hover ul.sub-menu{\n");
      out.write("    display: block;\n");
      out.write("    z-index: 2;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".body{\n");
      out.write("	z-index: 1;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".show_txt {\n");
      out.write("	display: inline-block;\n");
      out.write("	width: 100%;\n");
      out.write("	white-space: nowrap;\n");
      out.write("	overflow: hidden !important;\n");
      out.write("	text-overflow: ellipsis;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".menu1:hover {\n");
      out.write("	color: rgb(255, 200, 50);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".menu3:hover {\n");
      out.write("	background-color: rgb(60, 179, 113);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".menu2:hover {\n");
      out.write("	color: white;\n");
      out.write("	background-color: #708090;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".movie-title{\n");
      out.write("	font-family: 'Sen', sans-serif;\n");
      out.write("	font-size: 30px;\n");
      out.write("	color: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".show_txt{\n");
      out.write("	font-family: 'Sen', sans-serif;\n");
      out.write("	color: white;\n");
      out.write("	font-size: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".col-sm-6 .card-img-top {\n");
      out.write("	height: 200px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".movie-list:hover{\n");
      out.write("	transform: scale(1.2);\n");
      out.write("	cursor: pointer;\n");
      out.write("    position: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".movie-list:hover img{\n");
      out.write("    opacity: 0.5;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".movie-list:hover .movie-list-item{\n");
      out.write("	opacity: 1;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".movie-list-item{\n");
      out.write("	position: absolute;\n");
      out.write("	font-size: 40px;\n");
      out.write("	color: white;\n");
      out.write("	top: 35%;\n");
      out.write("    left: 70px;\n");
      out.write("    opacity: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".sum-episode{\n");
      out.write("	position: absolute;\n");
      out.write("	font-family: 'Sen', sans-serif;\n");
      out.write("	background-color: rgb(148, 142, 142);\n");
      out.write("	color: white;\n");
      out.write("	font-size: 13px;\n");
      out.write("	top: 5px;\n");
      out.write("    left: 20px;\n");
      out.write("    padding: 0 5px;\n");
      out.write("    border-radius: 5px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<body class=\"bg-dark\" style=\"font-family: Trirong, serif;\">\n");
      out.write("	\n");
      out.write("	<div class=\"container\">\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Head.jsp", out, false);
      out.write("\n");
      out.write("		<div id=\"search\" class=\"row\"></div>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"body\">\n");
      out.write("		");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("	</div>\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("	<!-- Edit -->\n");
      out.write("	<div class=\"modal fade\" id=\"edit\" tabindex=\"-1\"\n");
      out.write("		aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("		<div class=\"modal-dialog\">\n");
      out.write("			<div class=\"modal-content\">\n");
      out.write("				<div class=\"modal-header\">\n");
      out.write("					<h5 class=\"modal-title\" id=\"exampleModalLabel\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${phim.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("						aria-label=\"Close\">\n");
      out.write("						<span aria-hidden=\"true\">&times;</span>\n");
      out.write("					</button>\n");
      out.write("				</div>\n");
      out.write("				<form action=\"edit\" method=\"post\">\n");
      out.write("					<div class=\"modal-body\">\n");
      out.write("						<input name=\"id\" id=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${phim.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\n");
      out.write("							style=\"display: none;\"> <label for=\"type\"><b>Kiểu:</b></label>\n");
      out.write("						<input type=\"text\" class=\"form-control\" name=\"type\" id=\"type\"\n");
      out.write("							value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${phim.type }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><label for=\"category\"><b>Thể\n");
      out.write("								loại:</b></label> <input type=\"text\" class=\"form-control\" name=\"category\"\n");
      out.write("							id=\"category\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${phim.category}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><label\n");
      out.write("							for=\"episode\"><b>Tập:</b></label> <input type=\"text\"\n");
      out.write("							class=\"form-control\" name=\"episode\" id=\"episode\"\n");
      out.write("							value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${phim.episode }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><label for=\"episodeURL\"><b>URL:</b></label>\n");
      out.write("						<input type=\"text\" class=\"form-control\" name=\"episodeURL\"\n");
      out.write("							id=\"episodeURL\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${phim.episodeURL }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><label\n");
      out.write("							for=\"imageURL\"><b>Ảnh:</b></label> <input type=\"text\"\n");
      out.write("							class=\"form-control\" name=\"imageURL\" id=\"imageURL\"\n");
      out.write("							value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${phim.imageURL }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><label for=\"title\"><b>Tiêu\n");
      out.write("								đề:</b></label> <input type=\"text\" class=\"form-control\" name=\"title\"\n");
      out.write("							id=\"title\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${phim.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-footer\">\n");
      out.write("						<button type=\"submit\" class=\"btn btn-primary\">Cập nhật</button>\n");
      out.write("					</div>\n");
      out.write("				</form>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- Rempve -->\n");
      out.write("	<div class=\"modal fade\" id=\"remove\" tabindex=\"-1\"\n");
      out.write("		aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("		<div class=\"modal-dialog\">\n");
      out.write("			<div class=\"modal-content\">\n");
      out.write("				<div class=\"modal-header\">\n");
      out.write("					<h5 class=\"modal-title\" id=\"exampleModalLabel\">Có muốn xóa\n");
      out.write("						không ?</h5>\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("						aria-label=\"Close\">\n");
      out.write("						<span aria-hidden=\"true\">&times;</span>\n");
      out.write("					</button>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"modal-footer\">\n");
      out.write("					<button type=\"button\" class=\"btn btn-secondary\"\n");
      out.write("						data-dismiss=\"modal\">Không</button>\n");
      out.write("					<form action=\"remove\" method=\"post\">\n");
      out.write("						<input name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${phim.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"display: none;\">\n");
      out.write("						<button type=\"submit\" class=\"btn btn-primary\">Có</button>\n");
      out.write("					</form>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<script>\n");
      out.write("		function report() {\n");
      out.write("			let id = document.getElementById(\"id\").value;\n");
      out.write("			$.ajax({\n");
      out.write("				url : \"/phimmoi/report\",\n");
      out.write("				type : \"post\",\n");
      out.write("				data : {\n");
      out.write("					id : id\n");
      out.write("				},\n");
      out.write("				success : function(data) {\n");
      out.write("\n");
      out.write("				}\n");
      out.write("\n");
      out.write("			});\n");
      out.write("\n");
      out.write("			alert('Báo cáo thành công');\n");
      out.write("		}\n");
      out.write("\n");
      out.write("		function searchByName(param) {\n");
      out.write("			var txtSearch = param.value;\n");
      out.write("			$.ajax({\n");
      out.write("				url : \"/phimmoi/searchByName\",\n");
      out.write("				type : \"post\",\n");
      out.write("				data : {\n");
      out.write("					txt : txtSearch\n");
      out.write("				},\n");
      out.write("				success : function(data) {\n");
      out.write("					var row3 = document.getElementById(\"search\");\n");
      out.write("					row3.innerHTML = data;\n");
      out.write("				}\n");
      out.write("\n");
      out.write("			});\n");
      out.write("		}\n");
      out.write("\n");
      out.write("		function phanHoi(comment_id) {\n");
      out.write("			document.getElementById(comment_id).style.display = \"inline\";\n");
      out.write("		}\n");
      out.write("	</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WatchMovie.jsp(271,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${phim!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("			<div class=\"container\">\n");
          out.write("				<p style=\"color: rgb(255, 200, 50);\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${phim.type }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/\n");
          out.write("					");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${phim.category}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(' ');
          out.write('/');
          out.write(' ');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${phim.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\n");
          out.write("				");
          if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("				<div class=\"row\">\n");
          out.write("					<div class=\"col-sm-12\">\n");
          out.write("						<p style=\"color: rgb(240, 240, 240);\">\n");
          out.write("							Lượt xem: ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${phim.view}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" <i class=\"bi bi-eye\"></i>\n");
          out.write("						</p>\n");
          out.write("					</div>\n");
          out.write("					<div class=\"col-sm-1\" onclick=\"report()\"\n");
          out.write("						style=\"color: rgb(240, 240, 240); font-size: 25px;\">\n");
          out.write("						<i class=\"bi bi-flag-fill\"></i>\n");
          out.write("					</div>\n");
          out.write("					");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("				</div>\n");
          out.write("				<iframe class=\"ifra\" width=100% src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${phim.episodeURL }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\n");
          out.write("					title=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${phim.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" frameborder=\"0\"\n");
          out.write("					allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\"\n");
          out.write("					allowfullscreen></iframe>\n");
          out.write("				");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("				");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Comment.jsp", out, false);
          out.write("\n");
          out.write("				<hr\n");
          out.write("					style=\"height: 1px; border: none; background-color: rgb(240, 240, 240);\">\n");
          out.write("				<h3 style=\"color: rgb(255, 200, 50);padding: 30px 0;\">CÓ THỂ BẠN MUỐN XEM</h3>\n");
          out.write("	\n");
          out.write("				<div class=\"row\">\n");
          out.write("					");
          if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("	\n");
          out.write("				</div>\n");
          out.write("			</div>\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WatchMovie.jsp(275,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boPhim!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("					<p class=\"movie-title\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${phim.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" - Tập ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${phim.episode }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WatchMovie.jsp(288,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.admin!=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("						<div class=\"col-sm-1\">\n");
          out.write("							<i data-toggle=\"modal\" data-target=\"#edit\" class=\"bi bi-hammer\"\n");
          out.write("								style=\"color: rgb(240, 240, 240); font-size: 25px;\"></i>\n");
          out.write("						</div>\n");
          out.write("						<div class=\"col-sm-1\">\n");
          out.write("							<i data-toggle=\"modal\" data-target=\"#remove\" class=\"bi bi-trash\"\n");
          out.write("								style=\"color: rgb(240, 240, 240); font-size: 25px;\"></i>\n");
          out.write("						</div>\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WatchMovie.jsp(303,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WatchMovie.jsp(303,4) '${boPhim}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${boPhim}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WatchMovie.jsp(303,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("o");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("					<span class=\"btn ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.episode==phim.episode?\"btn-danger\":\"btn-secondary\" }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" menu3\"><a\n");
            out.write("						style=\"color: rgb(240, 240, 240); padding: 0px;\" class=\"nav-link\"\n");
            out.write("						href=\"detail?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.episode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></span>\n");
            out.write("				");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WatchMovie.jsp(314,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WatchMovie.jsp(314,5) '${phimTuongTu}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${phimTuongTu}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WatchMovie.jsp(314,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("o");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("						<div class=\"col-12 col-md-4 col-xl-2 col-lg-3 col-sm-6 movie-list\">\n");
            out.write("							<a href=\"detail?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"> <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.imageURL }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\n");
            out.write("								class=\"card-img-top\" alt=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\n");
            out.write("								<p class=\"sum-episode\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.sumEpisode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" Tập</p>\n");
            out.write("								<i class=\"fas fa-play-circle movie-list-item\"></i>\n");
            out.write("								<p class=\"show_txt\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p></a>\n");
            out.write("						</div>\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
